# -*- coding: utf-8 -*-
"""projet_finish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTLOG2NLfUE_81HOr0XXiKYZwC1j3LS-

**Introduction**
La cybersécurité est devenue un enjeu stratégique majeur à l’ère numérique, où les systèmes d’information sont constamment menacés par des attaques de plus en plus sophistiquées. Ce projet vise à développer un modèle de machine learning performant capable de détecter et classifier automatiquement les types d’attaques réseau à partir d’un dataset d'intrusion, dans une logique de prévention proactive des intrusions.

**L’objectif est double** : proposer une analyse approfondie des caractéristiques des attaques pour mieux les comprendre, et entraîner plusieurs modèles de classification afin d’identifier la meilleure approche algorithmique pour détecter même les attaques les plus rares.

**Présentation complète du projet**

**1. Préparation et analyse exploratoire des données**
Le dataset utilisé provient d’un environnement simulé d’intrusion réseau. Il contient des milliers de connexions réseau, chacune annotée avec un type d’attaque ou comme "normale". Une analyse exploratoire complète a permis :

de visualiser la répartition des types d’attaques,

de détecter des déséquilibres de classes importants,

d’identifier des variables fortement asymétriques et des outliers,

de générer des statistiques descriptives et des heatmaps de corrélation.

**2. Prétraitement et ingénierie des données**
Encodage des variables catégorielles (protocol_type, service, flag).

Création de nouvelles features (total_bytes, bytes_ratio, log_src_bytes, etc.).

Normalisation et traitement des valeurs extrêmes.

Application de SMOTE pour rééquilibrer les classes minoritaires.

**3. Modélisation**
Différents modèles de classification ont été entraînés :

Random Forest (brute, avec top 5 features, avec SMOTE, avec hyperparamètres optimisés),

CatBoost (brut et optimisé),

XGBoost, LightGBM, MLPClassifier, Decision Tree, Extra Trees.

Chaque modèle a été évalué selon la précision, le rappel, le f1-score, et les résultats ont été comparés en particulier sur la classe minoritaire (classe 4).

**4. Résultats principaux**
Sans rééquilibrage, les modèles peinaient à détecter les attaques rares.

SMOTE a significativement amélioré le rappel et le f1-score des classes minoritaires.

Le Random Forest optimisé + SMOTE et le CatBoost optimisé ont donné les meilleurs compromis entre performance globale et détection des classes rares.

**5. Visualisations**
Matrices de confusion, courbes d’apprentissage, pairplots, heatmaps de corrélation, barplots de f1-score par classe.

Comparaison graphique des modèles sur la classe 4 (la plus difficile à détecter).
"""

#import des modules
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from collections import Counter
from sklearn.model_selection import learning_curve
from sklearn.model_selection import cross_val_score
from imblearn.over_sampling import SMOTE
!pip install catboost
from catboost import CatBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import confusion_matrix, classification_report
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
import re

#importation du dataset
dataset = pd.read_csv("/content/drive/MyDrive/Intrusion_detection_classifier/dataset.csv")

# Analyse exploratoire du dataset

# Aperçu des premières lignes
print("Aperçu du dataset :")
display(dataset.head())

# Dimensions du dataset
print(f"Nombre de lignes : {dataset.shape[0]}")
print(f"Nombre de colonnes : {dataset.shape[1]}")

# Types de données et valeurs manquantes
print("\nTypes de données et valeurs manquantes :")
print(dataset.info())

# Statistiques descriptives
print("\nStatistiques descriptives :")
display(dataset.describe(include='all'))

# Répartition des classes cibles
print("\nRépartition des types d'attaque :")
display(dataset['Attack Type'].value_counts(normalize=True).rename('proportion').to_frame().join(dataset['Attack Type'].value_counts().rename('count')))

# Visualisation de la distribution des classes
import matplotlib.pyplot as plt
plt.figure(figsize=(6,4))
dataset['Attack Type'].value_counts().plot(kind='bar')
plt.title("Répartition des types d'attaque")
plt.xlabel("Type d'attaque (encodé)")
plt.ylabel("Nombre d'occurrences")
plt.tight_layout()
plt.show()

"""## Statistiques descriptives des variables numériques (`desc_stats`)

Le tableau `desc_stats` présente les principales statistiques descriptives (moyenne, médiane, écart-type, minimum, maximum) pour chaque variable numérique du dataset.

- **Variables fortement asymétriques** : `src_bytes`, `dst_bytes`, `total_bytes`, `bytes_ratio` présentent des moyennes très supérieures à la médiane et des maximums très élevés, indiquant la présence de valeurs extrêmes (outliers).
- **Variables majoritairement nulles** : Plusieurs variables comme `urgent`, `num_failed_logins`, `root_shell`, `su_attempted`, `num_shells`, `is_host_login`, `num_outbound_cmds` ont une médiane à 0 et une moyenne très faible, ce qui montre qu’elles sont rarement activées.
- **Variables de taux** : Les variables de type taux (`serror_rate`, `rerror_rate`, etc.) ont des moyennes faibles et une médiane à 0, mais peuvent atteindre 1, ce qui indique que la plupart des connexions sont « normales », mais certaines sont entièrement anormales.
- **Variables catégorielles encodées** : `protocol_type`, `service`, `flag` sont encodées en valeurs numériques, la médiane et la moyenne donnent une idée de la répartition des catégories.
- **Présence d’outliers** : L’écart-type très élevé pour certaines variables (ex : `src_bytes`, `dst_bytes`) confirme la présence de valeurs aberrantes, ce qui peut influencer les modèles de machine learning.

**Conclusion :**
Le dataset contient des variables très hétérogènes, avec des distributions souvent très déséquilibrées et de nombreux outliers. Une attention particulière doit être portée au prétraitement (normalisation, gestion des valeurs extrêmes) avant l’entraînement des modèles.

"""

# Statistiques descriptives pour chaque colonne numérique
desc_stats = dataset.describe().T[['mean', '50%', 'std', 'min', 'max']]
desc_stats.rename(columns={'50%': 'median'}, inplace=True)
display(desc_stats)

# Identification des valeurs aberrantes (outliers) par la méthode de l'écart interquartile (IQR)
outliers = {}
for col in dataset.select_dtypes(include=['int64', 'float64']).columns:
    Q1 = dataset[col].quantile(0.25)
    Q3 = dataset[col].quantile(0.75)
    IQR = Q3 - Q1
    outlier_mask = (dataset[col] < (Q1 - 1.5 * IQR)) | (dataset[col] > (Q3 + 1.5 * IQR))
    outliers[col] = dataset[col][outlier_mask]
    print(f"{col}: {outlier_mask.sum()} outliers")

# Analyse de la distribution des colonnes catégoriques
categorical_cols = ['protocol_type', 'service', 'flag', 'target', 'Attack Type']
for col in categorical_cols:
    print(f"\nDistribution de {col}:")
    display(dataset[col].value_counts(normalize=True).rename('proportion').to_frame().join(dataset[col].value_counts().rename('count')))

# Calculer la matrice de corrélation pour les colonnes numériques
corr_matrix = dataset.corr(numeric_only=True)

# Afficher la heatmap des corrélations
plt.figure(figsize=(18, 14))
sns.heatmap(corr_matrix, cmap='coolwarm', center=0, annot=False, fmt=".2f")
plt.title("Heatmap des corrélations entre les variables numériques")
plt.tight_layout()
plt.show()

# Répartition des types d'attaques (Attack Type)
print("Répartition des types d'attaques :")
display(dataset['Attack Type'].value_counts(normalize=True).rename('proportion').to_frame().join(dataset['Attack Type'].value_counts().rename('count')))

# Répartition des cibles (target)
print("\nRépartition des cibles (target) :")
display(dataset['target'].value_counts(normalize=True).rename('proportion').to_frame().join(dataset['target'].value_counts().rename('count')))

# Identifier les attaques les plus fréquentes
top_attack = dataset['Attack Type'].value_counts().idxmax()
print(f"\nCaractéristiques des attaques les plus fréquentes (Attack Type = {top_attack}):")
top_attack_df = dataset[dataset['Attack Type'] == top_attack]

# Protocole le plus fréquent
proto = top_attack_df['protocol_type'].value_counts().idxmax()
print(f"Protocole le plus fréquent : {proto}")

# Service le plus fréquent
service = top_attack_df['service'].value_counts().idxmax()
print(f"Service le plus fréquent : {service}")

# Flag le plus fréquent
flag = top_attack_df['flag'].value_counts().idxmax()
print(f"Flag le plus fréquent : {flag}")

# Affichage détaillé
print("\nDistribution des protocoles, services et flags pour l'attaque la plus fréquente :")
display(top_attack_df[['protocol_type', 'service', 'flag']].apply(pd.Series.value_counts).fillna(0))

# Supposons que chaque ligne représente un événement dans l'ordre chronologique
# On crée une colonne "index_time" représentant le temps fictif (ordre d'arrivée)
dataset['index_time'] = dataset.index

# Calculer le nombre d'attaques par tranche de temps (par exemple, par tranche de 10 000 événements)
window_size = 10000
dataset['is_attack'] = (dataset['Attack Type'] != 0).astype(int)
attack_counts = dataset.groupby(dataset['index_time'] // window_size)['is_attack'].sum()

plt.figure(figsize=(12, 5))
plt.plot(attack_counts.index * window_size, attack_counts.values, marker='o')
plt.title("Nombre d'attaques détectées par tranche de 10 000 événements")
plt.xlabel("Index (approximation temporelle)")
plt.ylabel("Nombre d'attaques")
plt.grid(True)
plt.tight_layout()
plt.show()

# Analyse de la durée moyenne des attaques par tranche
attack_duration = dataset[dataset['is_attack'] == 1].groupby(dataset['index_time'] // window_size)['duration'].mean()
plt.figure(figsize=(12, 5))
plt.plot(attack_duration.index * window_size, attack_duration.values, marker='x', color='red')
plt.title("Durée moyenne des attaques par tranche de 10 000 événements")
plt.xlabel("Index (approximation temporelle)")
plt.ylabel("Durée moyenne (duration)")
plt.grid(True)
plt.tight_layout()
plt.show()

# Encoder les colonnes catégoriques
dataset['Attack Type'] = dataset['Attack Type'].astype('category').cat.codes
categorical_columns = dataset.select_dtypes(include=['object']).columns
for col in categorical_columns:
    dataset[col] = dataset[col].astype('category').cat.codes

# Séparer les caractéristiques et la cible
X = dataset.drop(columns=['target', 'Attack Type'])
y = dataset['Attack Type']

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Entraîner un modèle Random Forest
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Évaluer le modèle
y_pred = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

conf_matrix, class_report

# Analyse des relations entre src_bytes, dst_bytes, count, srv_count
cols_to_plot = ['src_bytes', 'dst_bytes', 'count', 'srv_count', 'is_attack']

# Pairplot pour visualiser les relations et la séparation attaque/non-attaque
sns.pairplot(dataset[cols_to_plot], hue='is_attack', plot_kws={'alpha': 0.3})
plt.suptitle("Relations entre src_bytes, dst_bytes, count, srv_count et la variable cible", y=1.02)
plt.show()

# Matrice de corrélation centrée sur la variable cible
corr = dataset[cols_to_plot].corr()
plt.figure(figsize=(6, 5))
sns.heatmap(corr, annot=True, cmap='coolwarm', center=0)
plt.title("Corrélations entre src_bytes, dst_bytes, count, srv_count et is_attack")
plt.tight_layout()
plt.show()

# Importance des variables selon le modèle Random Forest déjà entraîné
importances = model.feature_importances_
features = X_train.columns
indices = importances.argsort()[::-1]

plt.figure(figsize=(10, 5))
plt.title("Top 10 variables influençant la probabilité d'une attaque (Random Forest)")
top_n = 10
plt.bar(range(top_n), importances[indices[:top_n]], align="center")
plt.xticks(range(top_n), features[indices[:top_n]], rotation=45)
plt.ylabel("Importance")
plt.tight_layout()
plt.show()

print("Top 10 variables les plus importantes pour la détection d'une attaque :")
for i in range(top_n):
    print(f"{i+1}. {features[indices[i]]} (importance: {importances[indices[i]]:.3f})")

# Étude des caractéristiques des attaques vs comportements normaux

# 1. Analyse des distributions pour protocol_type, service, flag selon la variable cible
fig, axes = plt.subplots(1, 3, figsize=(18, 4))
sns.countplot(x='protocol_type', hue='is_attack', data=dataset, ax=axes[0])
axes[0].set_title("Protocol type selon attaque ou normal")
sns.countplot(x='service', hue='is_attack', data=dataset, ax=axes[1])
axes[1].set_title("Service selon attaque ou normal")
sns.countplot(x='flag', hue='is_attack', data=dataset, ax=axes[2])
axes[2].set_title("Flag selon attaque ou normal")
plt.tight_layout()
plt.show()

# 2. Statistiques descriptives pour quelques variables continues selon attaque ou normal
cols_to_compare = ['src_bytes', 'dst_bytes', 'count', 'srv_count', 'serror_rate', 'rerror_rate']
display(dataset.groupby('is_attack')[cols_to_compare].describe().T)

# 3. Importance des variables selon le modèle Random Forest déjà entraîné
importances = model.feature_importances_
features = X_train.columns
indices = importances.argsort()[::-1]

plt.figure(figsize=(10, 5))
plt.title("Top 10 variables différenciant attaque/normal (Random Forest)")
top_n = 10
plt.bar(range(top_n), importances[indices[:top_n]], align="center")
plt.xticks(range(top_n), features[indices[:top_n]], rotation=45)
plt.ylabel("Importance")
plt.tight_layout()
plt.show()

print("Variables les plus discriminantes pour la détection d'une attaque :")
for i in range(top_n):
    print(f"{i+1}. {features[indices[i]]} (importance: {importances[indices[i]]:.3f})")

# Sélection des colonnes liées aux erreurs
error_cols = ['serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate']

# Statistiques descriptives pour chaque type d'erreur
display(dataset[error_cols].describe())

# Distribution des taux d'erreur pour chaque type
fig, axes = plt.subplots(2, 2, figsize=(14, 8))
for ax, col in zip(axes.flatten(), error_cols):
    sns.histplot(dataset[col], bins=50, kde=True, ax=ax)
    ax.set_title(f"Distribution de {col}")
plt.tight_layout()
plt.show()

# Analyse par type d'attaque
for col in error_cols:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x='Attack Type', y=col, data=dataset)
    plt.title(f"{col} selon le type d'attaque")
    plt.show()

# Corrélation entre les taux d'erreur et la variable cible
corrs = dataset[error_cols + ['Attack Type']].corr()
display(corrs['Attack Type'].sort_values(ascending=False))

cols_network = ['same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count']

# Statistiques descriptives
display(dataset[cols_network].describe())

# Visualisation des distributions
fig, axes = plt.subplots(2, 3, figsize=(18, 8))
for i, col in enumerate(cols_network):
    ax = axes.flatten()[i]
    sns.histplot(dataset[col], bins=50, kde=True, ax=ax)
    ax.set_title(f"Distribution de {col}")
axes.flatten()[-1].axis('off')
plt.tight_layout()
plt.show()

# Analyse selon la variable cible (is_attack)
for col in cols_network:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x='is_attack', y=col, data=dataset)
    plt.title(f"{col} selon attaque (1) ou normal (0)")
    plt.xlabel("is_attack")
    plt.ylabel(col)
    plt.show()

# Corrélations entre ces variables et la cible
corrs = dataset[cols_network + ['is_attack']].corr()
display(corrs['is_attack'].sort_values(ascending=False))

# Segmentation des données par type d'attaque
attack_types = dataset['Attack Type'].unique()
attack_segments = {}

for attack in attack_types:
    segment = dataset[dataset['Attack Type'] == attack]
    attack_segments[attack] = segment
    print(f"Type d'attaque {attack} : {len(segment)} échantillons")
    display(segment.describe())

# Exemple d'accès à un segment spécifique :
# attack_segments[0]  # Segment pour le type d'attaque 0 (normal)

# Liste des colonnes numériques à visualiser
num_cols = ['src_bytes', 'dst_bytes', 'count', 'srv_count', 'serror_rate', 'rerror_rate', 'same_srv_rate', 'diff_srv_rate']

# Histogrammes
fig, axes = plt.subplots(2, 4, figsize=(20, 8))
for ax, col in zip(axes.flatten(), num_cols):
    sns.histplot(dataset[col], bins=50, kde=True, ax=ax)
    ax.set_title(f"Distribution de {col}")
plt.tight_layout()
plt.show()

# Box plots pour détecter les valeurs aberrantes
fig, axes = plt.subplots(2, 4, figsize=(20, 8))
for ax, col in zip(axes.flatten(), num_cols):
    sns.boxplot(x=dataset[col], ax=ax)
    ax.set_title(f"Boxplot de {col}")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='protocol_type', data=dataset)
plt.title("Fréquence des différents protocoles (protocol_type)")
plt.xlabel("Type de protocole (encodé)")
plt.ylabel("Nombre d'occurrences")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
sns.countplot(x='service', data=dataset, order=dataset['service'].value_counts().index)
plt.title("Fréquence des différents services (service)")
plt.xlabel("Service (encodé)")
plt.ylabel("Nombre d'occurrences")
plt.tight_layout()
plt.show()

# Pie chart pour la proportion des types d'attaques
attack_counts = dataset['Attack Type'].value_counts()
plt.figure(figsize=(7, 7))
plt.pie(attack_counts, labels=attack_counts.index, autopct='%1.1f%%', startangle=140, counterclock=False)
plt.title("Proportion des différents types d'attaques (Attack Type)")
plt.tight_layout()
plt.show()

# Bar plot pour la fréquence des cibles (target)
target_counts = dataset['target'].value_counts().sort_index()
plt.figure(figsize=(8, 5))
plt.bar(target_counts.index.astype(str), target_counts.values, color='skyblue')
plt.title("Fréquence des cibles (target)")
plt.xlabel("Valeur de target")
plt.ylabel("Nombre d'occurrences")
plt.tight_layout()
plt.show()

# Calcul de la matrice de corrélation pour les colonnes numériques
corr_matrix = dataset.corr(numeric_only=True)

plt.figure(figsize=(18, 14))
sns.heatmap(corr_matrix, cmap='coolwarm', center=0, annot=False, fmt=".2f")
plt.title("Heatmap des corrélations entre les variables numériques")
plt.tight_layout()
plt.show()

# Scatter plot entre serror_rate et srv_serror_rate
plt.figure(figsize=(7, 5))
plt.scatter(dataset['serror_rate'], dataset['srv_serror_rate'], alpha=0.2, s=5)
plt.xlabel('serror_rate')
plt.ylabel('srv_serror_rate')
plt.title('Relation entre serror_rate et srv_serror_rate')
plt.grid(True)
plt.tight_layout()
plt.show()

# Scatter plot entre rerror_rate et srv_rerror_rate
plt.figure(figsize=(7, 5))
plt.scatter(dataset['rerror_rate'], dataset['srv_rerror_rate'], alpha=0.2, s=5, color='orange')
plt.xlabel('rerror_rate')
plt.ylabel('srv_rerror_rate')
plt.title('Relation entre rerror_rate et srv_rerror_rate')
plt.grid(True)
plt.tight_layout()
plt.show()

# Scatter plot: same_srv_rate vs diff_srv_rate
plt.figure(figsize=(7, 5))
plt.scatter(dataset['same_srv_rate'], dataset['diff_srv_rate'], alpha=0.2, s=5)
plt.xlabel('same_srv_rate')
plt.ylabel('diff_srv_rate')
plt.title('Relation entre same_srv_rate et diff_srv_rate')
plt.grid(True)
plt.tight_layout()
plt.show()

# Scatter plot: dst_host_count vs dst_host_srv_count
plt.figure(figsize=(7, 5))
plt.scatter(dataset['dst_host_count'], dataset['dst_host_srv_count'], alpha=0.2, s=5, color='orange')
plt.xlabel('dst_host_count')
plt.ylabel('dst_host_srv_count')
plt.title('Relation entre dst_host_count et dst_host_srv_count')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
plt.scatter(dataset['src_bytes'], dataset['dst_bytes'], alpha=0.2, s=5)
plt.xlabel('src_bytes')
plt.ylabel('dst_bytes')
plt.title('Relation entre src_bytes et dst_bytes')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Entraîner un modèle de machine learning pour classifier les types d'attaques dans le dataset."""

# Encoder les colonnes catégoriques
dataset['Attack Type'] = dataset['Attack Type'].astype('category').cat.codes
categorical_columns = dataset.select_dtypes(include=['object']).columns
for col in categorical_columns:
    dataset[col] = dataset[col].astype('category').cat.codes

# Séparer les caractéristiques et la cible
X = dataset.drop(columns=['target', 'Attack Type'])
y = dataset['Attack Type']

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Entraîner un modèle Random Forest
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Évaluer le modèle
y_pred = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

conf_matrix, class_report

"""### Interprétation des résultats du modèle Random Forest

#### Matrice de confusion
La matrice de confusion montre la répartition des prédictions du modèle pour chaque classe :

- **Classe 0** : 117394 instances correctement classées.
- **Classe 1** : 29186 correctement classées, 2 et 4 erreurs mineures.
- **Classe 2** : 1246 correctement classées, 9 erreurs vers la classe 1.
- **Classe 3** : 335 correctement classées, 14 erreurs vers la classe 1.
- **Classe 4** : 9 correctement classées, 8 erreurs vers la classe 1.

#### Rapport de classification

- **Précision, rappel et f1-score** sont très élevés pour toutes les classes, surtout pour les classes majoritaires (0 et 1).
- **Classe 4** a un rappel plus faible (0.53), indiquant que le modèle a du mal à détecter tous les exemples de cette classe (beaucoup sont confondus avec la classe 1).
- **Exactitude globale** : 1.00 (très élevée, mais à relativiser en cas de déséquilibre des classes).
- **Macro avg** (moyenne non pondérée) : f1-score de 0.93, ce qui montre une bonne performance globale, mais légèrement pénalisée par la classe 4.
- **Weighted avg** (moyenne pondérée) : f1-score de 1.00, reflétant la forte proportion de classes majoritaires bien prédites.

**Conclusion :**  
Le modèle Random Forest classe très bien la majorité des attaques, mais a plus de difficultés sur les classes très minoritaires (notamment la classe 4). Il pourrait être utile d'explorer des techniques de rééquilibrage ou d'ajuster les paramètres pour améliorer la détection des classes rares.
"""

# Appliquer SMOTE pour rééquilibrer les classes sur l'ensemble d'entraînement
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Réentraîner le modèle Random Forest sur les données rééquilibrées
model_res = RandomForestClassifier(random_state=42)
model_res.fit(X_train_res, y_train_res)

# Évaluer le nouveau modèle
y_pred_res = model_res.predict(X_test)
conf_matrix_res = confusion_matrix(y_test, y_pred_res)
class_report_res = classification_report(y_test, y_pred_res)

print(conf_matrix_res)
print(class_report_res)

"""Creating a new notebook:
GitHub Copilot

### Interprétation des résultats après rééquilibrage (SMOTE)

#### Matrice de confusion
- **Classe 0** : 117394 instances correctement classées, aucune confusion.
- **Classe 1** : 29185 bien classées, 3 confondues avec la classe 2, 4 avec la classe 3.
- **Classe 2** : 1249 bien classées, 6 confondues avec la classe 1.
- **Classe 3** : 339 bien classées, 10 confondues avec la classe 1.
- **Classe 4** : 13 bien classées, 2 confondues avec la classe 1, 2 avec la classe 3.

#### Rapport de classification

- **Classes majoritaires (0, 1, 2)** : Précision, rappel et f1-score parfaits (1.00).
- **Classe 3** : Légère baisse du rappel (0.97) et du f1-score (0.98), mais performance très élevée.
- **Classe 4** : Amélioration notable du rappel (0.76) et du f1-score (0.87) par rapport au modèle sans rééquilibrage, indiquant une meilleure détection des classes rares.

- **Macro avg** : f1-score de 0.97, montrant une performance globale équilibrée sur toutes les classes.
- **Weighted avg** : f1-score de 1.00, reflétant la forte proportion de classes majoritaires bien prédites.

**Conclusion :**  
L'utilisation de SMOTE a permis d'améliorer la détection des classes minoritaires, en particulier la classe 4, tout en maintenant une excellente performance globale. Le modèle est désormais plus robuste face au déséquilibre des classes.
"""

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.title("Matrice de confusion du modèle Random Forest")
plt.xlabel("Prédictions")
plt.ylabel("Vraies classes")
plt.show()

"""L’image précédente représente la matrice de confusion du modèle Random Forest avant rééquilibrage des classes. Voici comment l’interpréter :

- **Classe 0** (majoritaire) : 117 394 instances correctement classées, aucune confusion avec d’autres classes.
- **Classe 1** : 29 186 bien classées, 2 confondues avec la classe 2 et 4 avec la classe 3.
- **Classe 2** : 1 246 bien classées, 9 confondues avec la classe 1.
- **Classe 3** : 335 bien classées, 14 confondues avec la classe 1.
- **Classe 4** (minoritaire) : 9 bien classées, 8 confondues avec la classe 1.

**Analyse :**
- Le modèle est très performant sur les classes majoritaires (0 et 1), avec très peu d’erreurs.
- Les classes minoritaires (notamment la classe 4) sont souvent confondues avec la classe 1, ce qui indique un déséquilibre des classes et une difficulté à détecter les attaques rares.
- La majorité des erreurs de classification concernent la confusion entre les classes minoritaires et la classe 1.

**Conclusion :**
Le modèle Random Forest détecte très bien les attaques fréquentes, mais il a du mal à identifier les attaques rares. Cela justifie l’utilisation de techniques de rééquilibrage comme SMOTE pour améliorer la détection des classes minoritaires.
"""

# Extraire les f1-scores du rapport de classification pour chaque classe

def extract_f1_scores(report):
    lines = report.strip().split('\n')
    f1_scores = []
    class_labels = []
    for line in lines[2:7]:  # Les 5 premières classes
        parts = re.split(r'\s+', line.strip())
        if len(parts) >= 4:
            class_labels.append(parts[0])
            f1_scores.append(float(parts[3]))
    return class_labels, f1_scores

labels, f1_before = extract_f1_scores(class_report)
_, f1_after = extract_f1_scores(class_report_res)

x = np.arange(len(labels))
width = 0.35

plt.figure(figsize=(8, 5))
plt.bar(x - width/2, f1_before, width, label='Avant SMOTE')
plt.bar(x + width/2, f1_after, width, label='Après SMOTE')
plt.ylabel('F1-score')
plt.xlabel('Classe')
plt.title('F1-score par classe avant et après rééquilibrage (SMOTE)')
plt.xticks(x, labels)
plt.ylim(0, 1.1)
plt.legend()
plt.tight_layout()
plt.show()

train_sizes, train_scores, test_scores = learning_curve(
    model, X_train, y_train, cv=5, scoring='f1_weighted',
    train_sizes=np.linspace(0.1, 1.0, 5), n_jobs=-1
)

train_scores_mean = np.mean(train_scores, axis=1)
test_scores_mean = np.mean(test_scores, axis=1)

plt.figure(figsize=(8, 5))
plt.plot(train_sizes, train_scores_mean, 'o-', color='r', label='Score d\'entraînement')
plt.plot(train_sizes, test_scores_mean, 'o-', color='g', label='Score de validation')
plt.title('Courbe d\'apprentissage du modèle Random Forest')
plt.xlabel('Taille de l\'ensemble d\'entraînement')
plt.ylabel('Score F1 pondéré')
plt.legend(loc='best')
plt.grid()
plt.tight_layout()
plt.show()

# Analyse du surapprentissage (overfitting) à partir des courbes d'apprentissage

print("Score moyen d'entraînement (train):", train_scores_mean)
print("Score moyen de validation (test):", test_scores_mean)

# Vérification visuelle de l'écart entre les scores
gap = train_scores_mean - test_scores_mean
print("Écart moyen entre train et test :", gap)

if (gap < 0.01).all():
    print("Il n'y a pas de signe d'overfitting : les scores d'entraînement et de validation sont très proches.")
else:
    print("Attention : un écart significatif entre les scores peut indiquer un surapprentissage.")

dataset['total_bytes'] = dataset['src_bytes'] + dataset['dst_bytes']
dataset['bytes_ratio'] = dataset['src_bytes'] / (dataset['dst_bytes'] + 1)
    # Exemple de transformation logarithmique
dataset['log_src_bytes'] = (dataset['src_bytes'] + 1).apply(np.log)
dataset['log_dst_bytes'] = (dataset['dst_bytes'] + 1).apply(np.log)

dataset.columns

# Encoder les colonnes catégoriques
dataset['Attack Type'] = dataset['Attack Type'].astype('category').cat.codes
categorical_columns = dataset.select_dtypes(include=['object']).columns
for col in categorical_columns:
    dataset[col] = dataset[col].astype('category').cat.codes

# Séparer les caractéristiques et la cible
X = dataset.drop(columns=['target', 'Attack Type'])
y = dataset['Attack Type']

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Entraîner un modèle Random Forest
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Évaluer le modèle
y_pred = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

conf_matrix, class_report

"""### Interprétation de la matrice de confusion et du rapport de classification

#### Matrice de confusion

| Classe réelle \ Prédite | 0      | 1      | 2    | 3    | 4   |
|-------------------------|--------|--------|------|------|-----|
| **0**                   | 117394 | 0      | 0    | 0    | 0   |
| **1**                   | 0      | 29187  | 3    | 2    | 0   |
| **2**                   | 0      | 6      | 1249 | 0    | 0   |
| **3**                   | 0      | 8      | 0    | 340  | 1   |
| **4**                   | 0      | 6      | 0    | 0    | 11  |

- **Classe 0** : 117 394 instances parfaitement classées.
- **Classe 1** : 29 187 bien classées, 3 confondues avec la classe 2, 2 avec la classe 3.
- **Classe 2** : 1 249 bien classées, 6 confondues avec la classe 1.
- **Classe 3** : 340 bien classées, 8 confondues avec la classe 1, 1 avec la classe 4.
- **Classe 4** : 11 bien classées, 6 confondues avec la classe 1.

#### Rapport de classification

- **Classe 0, 1, 2** : Précision, rappel et f1-score parfaits (1.00).
- **Classe 3** : Précision 0.99, rappel 0.97, f1-score 0.98.
- **Classe 4** : Précision 0.92, rappel 0.65, f1-score 0.76 (le modèle a du mal à détecter tous les exemples de cette classe).

- **Exactitude globale** : 1.00 (très élevée).
- **Macro avg** : f1-score de 0.95, rappel de 0.92 (moyenne non pondérée).
- **Weighted avg** : f1-score de 1.00 (moyenne pondérée par le nombre d’exemples).

**Conclusion :**
Le modèle Random Forest est très performant sur les classes majoritaires, mais il a plus de difficultés à détecter la classe 4 (minoritaire), qui est souvent confondue avec la classe 1. Cela indique un déséquilibre des classes et justifie l’utilisation de techniques de rééquilibrage.
"""

# Appliquer SMOTE pour rééquilibrer les classes sur l'ensemble d'entraînement
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Réentraîner le modèle Random Forest sur les données rééquilibrées
model_res = RandomForestClassifier(random_state=42)
model_res.fit(X_train_res, y_train_res)

# Évaluer le nouveau modèle
y_pred_res = model_res.predict(X_test)
conf_matrix_res = confusion_matrix(y_test, y_pred_res)
class_report_res = classification_report(y_test, y_pred_res)

print(conf_matrix_res)
print(class_report_res)

"""### Interprétation de la matrice de confusion et du rapport de classification après SMOTE

#### Matrice de confusion

| Classe réelle \ Prédite | 0      | 1      | 2    | 3    | 4   |
|-------------------------|--------|--------|------|------|-----|
| **0**                   | 117394 | 0      | 0    | 0    | 0   |
| **1**                   | 0      | 29189  | 2    | 1    | 0   |
| **2**                   | 0      | 5      | 1250 | 0    | 0   |
| **3**                   | 0      | 6      | 0    | 343  | 0   |
| **4**                   | 0      | 2      | 0    | 2    | 13  |

- **Classe 0** : 117 394 instances parfaitement classées.
- **Classe 1** : 29 189 bien classées, 2 confondues avec la classe 2, 1 avec la classe 3.
- **Classe 2** : 1 250 bien classées, 5 confondues avec la classe 1.
- **Classe 3** : 343 bien classées, 6 confondues avec la classe 1.
- **Classe 4** : 13 bien classées, 2 confondues avec la classe 1, 2 avec la classe 3.

#### Rapport de classification

- **Classes 0, 1, 2** : Précision, rappel et f1-score parfaits (1.00).
- **Classe 3** : Précision 0.99, rappel 0.98, f1-score 0.99.
- **Classe 4** : Précision 1.00, rappel 0.76, f1-score 0.87 (meilleure détection des classes rares après SMOTE).

- **Exactitude globale** : 1.00 (très élevée).
- **Macro avg** : f1-score de 0.97, rappel de 0.95 (moyenne non pondérée).
- **Weighted avg** : f1-score de 1.00 (moyenne pondérée par le nombre d’exemples).

**Conclusion :**
L’application de SMOTE a permis d’améliorer la détection de la classe minoritaire (classe 4), avec un rappel et un f1-score nettement supérieurs à ceux du modèle initial. Le modèle reste excellent sur les classes majoritaires et devient plus robuste face au déséquilibre des classes.
"""

# Extraire les f1-scores du rapport de classification pour chaque classe

def extract_f1_scores(report):
    lines = report.strip().split('\n')
    f1_scores = []
    class_labels = []
    for line in lines[2:7]:  # Les 5 premières classes
        parts = re.split(r'\s+', line.strip())
        if len(parts) >= 4:
            class_labels.append(parts[0])
            f1_scores.append(float(parts[3]))
    return class_labels, f1_scores

labels, f1_before = extract_f1_scores(class_report)
_, f1_after = extract_f1_scores(class_report_res)

x = np.arange(len(labels))
width = 0.35

plt.figure(figsize=(8, 5))
plt.bar(x - width/2, f1_before, width, label='Avant SMOTE')
plt.bar(x + width/2, f1_after, width, label='Après SMOTE')
plt.ylabel('F1-score')
plt.xlabel('Classe')
plt.title('F1-score par classe avant et après rééquilibrage (SMOTE)')
plt.xticks(x, labels)
plt.ylim(0, 1.1)
plt.legend()
plt.tight_layout()
plt.show()

importances = model.feature_importances_
features = X_train.columns

# Tri des variables par importance décroissante
indices = importances.argsort()[::-1]
plt.figure(figsize=(12, 6))
plt.title("Importance des variables (Random Forest)")
plt.bar(range(len(importances)), importances[indices], align="center")
plt.xticks(range(len(importances)), features[indices], rotation=90)
plt.ylabel("Importance")
plt.tight_layout()
plt.show()

# Appliquer SMOTE pour rééquilibrer les classes sur l'ensemble d'entraînement
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Réentraîner le modèle Random Forest sur les données rééquilibrées
model_res = RandomForestClassifier(random_state=42,max_depth=20,min_samples_leaf=1,min_samples_split=5,n_estimators=100)
model_res.fit(X_train_res, y_train_res)

# Évaluer le nouveau modèle
y_pred_res = model_res.predict(X_test)
conf_matrix_res = confusion_matrix(y_test, y_pred_res)
class_report_res = classification_report(y_test, y_pred_res)

print(conf_matrix_res)
print(class_report_res)

"""### Interprétation de la matrice de confusion et du rapport de classification après SMOTE et optimisation

#### Matrice de confusion

| Classe réelle \ Prédite | 0      | 1      | 2    | 3   | 4  |
|-------------------------|--------|--------|------|-----|----|
| **0**                   | 117394 | 0      | 0    | 0   | 0  |
| **1**                   | 0      | 29185  | 3    | 4   | 0  |
| **2**                   | 0      | 5      | 1250 | 0   | 0  |
| **3**                   | 0      | 8      | 0    | 341 | 0  |
| **4**                   | 0      | 1      | 0    | 0   | 16 |

- **Classe 0** : 117 394 instances parfaitement classées.
- **Classe 1** : 29 185 bien classées, 3 confondues avec la classe 2, 4 avec la classe 3.
- **Classe 2** : 1 250 bien classées, 5 confondues avec la classe 1.
- **Classe 3** : 341 bien classées, 8 confondues avec la classe 1.
- **Classe 4** : 16 bien classées, 1 confondue avec la classe 1.

#### Rapport de classification

- **Classes 0, 1, 2** : Précision, rappel et f1-score parfaits (1.00).
- **Classe 3** : Précision 0.99, rappel 0.98, f1-score 0.98.
- **Classe 4** : Précision 1.00, rappel 0.94, f1-score 0.97 (excellente détection de la classe rare).

- **Exactitude globale** : 1.00 (très élevée).
- **Macro avg** : f1-score de 0.99, rappel de 0.98 (moyenne non pondérée).
- **Weighted avg** : f1-score de 1.00 (moyenne pondérée par le nombre d’exemples).

**Conclusion :**
L’application de SMOTE et l’optimisation des hyperparamètres ont permis d’obtenir un modèle très performant, aussi bien sur les classes majoritaires que minoritaires. La classe 4 (rare) est désormais bien détectée, avec un rappel et un f1-score très élevés. Le modèle est robuste et équilibré face au déséquilibre des classes.
"""

# Entraînement du modèle CatBoost sur l'ensemble d'entraînement
catboost_model = CatBoostClassifier(verbose=0, random_state=42)
catboost_model.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred_catboost = catboost_model.predict(X_test)

# Évaluation du modèle
conf_matrix_catboost = confusion_matrix(y_test, y_pred_catboost)
class_report_catboost = classification_report(y_test, y_pred_catboost)

print(conf_matrix_catboost)
print(class_report_catboost)

"""### Interprétation de la matrice de confusion et du rapport de classification

#### Matrice de confusion

| Classe réelle \ Prédite | 0      | 1      | 2    | 3   | 4  |
|-------------------------|--------|--------|------|-----|----|
| **0**                   | 117394 | 0      | 0    | 0   | 0  |
| **1**                   | 1      | 29186  | 3    | 2   | 0  |
| **2**                   | 0      | 6      | 1249 | 0   | 0  |
| **3**                   | 0      | 7      | 0    | 342 | 0  |
| **4**                   | 0      | 2      | 0    | 1   | 14 |

- **Classe 0** : 117 394 instances parfaitement classées.
- **Classe 1** : 29 186 bien classées, 1 confondue avec la classe 0, 3 avec la classe 2, 2 avec la classe 3.
- **Classe 2** : 1 249 bien classées, 6 confondues avec la classe 1.
- **Classe 3** : 342 bien classées, 7 confondues avec la classe 1.
- **Classe 4** : 14 bien classées, 2 confondues avec la classe 1, 1 avec la classe 3.

#### Rapport de classification

- **Classes 0, 1, 2** : Précision, rappel et f1-score parfaits (1.00).
- **Classe 3** : Précision 0.99, rappel 0.98, f1-score 0.99.
- **Classe 4** : Précision 1.00, rappel 0.82, f1-score 0.90 (le modèle détecte mieux la classe rare, mais quelques exemples sont encore confondus).

- **Exactitude globale** : 1.00 (très élevée).
- **Macro avg** : f1-score de 0.98, rappel de 0.96 (moyenne non pondérée).
- **Weighted avg** : f1-score de 1.00 (moyenne pondérée par le nombre d’exemples).

**Conclusion :**
Le modèle est excellent sur les classes majoritaires et s’améliore nettement sur la classe minoritaire (classe 4), avec un rappel de 0.82 et un f1-score de 0.90. Les erreurs de classification concernent principalement la confusion entre la classe 4 et la classe 1, mais la performance globale reste très élevée.
"""

# Entraîner un MLP sur les 5 features les plus importantes
mlp_top5 = MLPClassifier(hidden_layer_sizes=(100,), max_iter=100, random_state=42)
mlp_top5.fit(X_train, y_train)
y_pred_mlp_top5 = mlp_top5.predict(X_test)

conf_matrix_mlp_top5 = confusion_matrix(y_test, y_pred_mlp_top5)
class_report_mlp_top5 = classification_report(y_test, y_pred_mlp_top5)

print(conf_matrix_mlp_top5)
print(class_report_mlp_top5)

# Entraîner un Decision Tree sur toutes les features
dt_full = DecisionTreeClassifier(random_state=42)
dt_full.fit(X_train, y_train)
y_pred_dt_full = dt_full.predict(X_test)

conf_matrix_dt_full = confusion_matrix(y_test, y_pred_dt_full)
class_report_dt_full = classification_report(y_test, y_pred_dt_full)

print(conf_matrix_dt_full)
print(class_report_dt_full)

# Entraîner Extra-Trees sur toutes les features
extra_trees_full = ExtraTreesClassifier(random_state=42)
extra_trees_full.fit(X_train, y_train)
y_pred_extra_full = extra_trees_full.predict(X_test)

conf_matrix_extra_full = confusion_matrix(y_test, y_pred_extra_full)
class_report_extra_full = classification_report(y_test, y_pred_extra_full)

print(conf_matrix_extra_full)
print(class_report_extra_full)

# Entraîner LightGBM sur toutes les features
lgbm_full = LGBMClassifier(random_state=42, verbose=-1)
lgbm_full.fit(X_train, y_train)
y_pred_lgbm_full = lgbm_full.predict(X_test)

conf_matrix_lgbm_full = confusion_matrix(y_test, y_pred_lgbm_full)
class_report_lgbm_full = classification_report(y_test, y_pred_lgbm_full)

print(conf_matrix_lgbm_full)
print(class_report_lgbm_full)

# Entraîner XGBoost sur toutes les features
xgb_full = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
xgb_full.fit(X_train, y_train)
y_pred_xgb_full = xgb_full.predict(X_test)

conf_matrix_xgb_full = confusion_matrix(y_test, y_pred_xgb_full)
class_report_xgb_full = classification_report(y_test, y_pred_xgb_full)

print(conf_matrix_xgb_full)
print(class_report_xgb_full)

# F1-score macro pour chaque modèle (extraits des rapports de classification)
f1_macros = [
    0.95,  # Random Forest (all features)
    0.83,  # Random Forest (top 5)
    0.99,  # Random Forest SMOTE+Opti
    0.98,  # CatBoost
    0.90,  # Decision Tree
    0.94,  # Extra Trees
    0.56,  # LightGBM
    0.97,  # XGBoost
    0.59   # MLP (top 5)
]

model_names = [
    'Random Forest (all features)', 'Random Forest (top 5)', 'Random Forest SMOTE+Opti',
    'CatBoost', 'Decision Tree', 'Extra Trees', 'LightGBM', 'XGBoost', 'MLP'
]

plt.figure(figsize=(12, 6))
bars = plt.bar(model_names, f1_macros, color='skyblue')
plt.ylabel('F1-score macro')
plt.title('Comparaison des performances (F1-score macro) des modèles')
plt.ylim(0, 1.1)
plt.xticks(rotation=30, ha='right')
for bar, score in zip(bars, f1_macros):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01, f"{score:.2f}", ha='center', va='bottom')
plt.tight_layout()
plt.show()

# Comparaison des modèles sur la capacité à prédire la classe minoritaire (classe 4)
# On extrait le f1-score de la classe 4 pour chaque modèle à partir des rapports de classification déjà présents

def extract_f1_class(report, class_idx=4):
    lines = report.strip().split('\n')
    # Les lignes des classes commencent à la 3ème ligne (index 2)
    class_line = lines[2 + class_idx]
    parts = re.split(r'\s+', class_line.strip())
    if len(parts) >= 4:
        return float(parts[3])
    return None

f1_cl4_rf = extract_f1_class(class_report)                # Random Forest (all features)
f1_cl4_rf_top5 = 0.03                                     # Random Forest (top 5), pris du résumé f1_macros
f1_cl4_rf_smote = extract_f1_class(class_report_res)      # Random Forest SMOTE+Opti
f1_cl4_catboost = extract_f1_class(class_report_catboost) # CatBoost
f1_cl4_dt = extract_f1_class(class_report_dt_full)        # Decision Tree
f1_cl4_extra = extract_f1_class(class_report_extra_full)  # Extra Trees
f1_cl4_lgbm = extract_f1_class(class_report_lgbm_full)    # LightGBM
f1_cl4_xgb = extract_f1_class(class_report_xgb_full)      # XGBoost
f1_cl4_mlp = extract_f1_class(class_report_mlp_top5)      # MLP (top 5)

f1_cl4_scores = [
    f1_cl4_rf, f1_cl4_rf_top5, f1_cl4_rf_smote, f1_cl4_catboost,
    f1_cl4_dt, f1_cl4_extra, f1_cl4_lgbm, f1_cl4_xgb, f1_cl4_mlp
]

plt.figure(figsize=(12, 6))
bars = plt.bar(model_names, f1_cl4_scores, color='salmon')
plt.ylabel('F1-score classe minoritaire (classe 4)')
plt.title('Comparaison des modèles sur la prédiction de la classe minoritaire')
plt.ylim(0, 1.1)
plt.xticks(rotation=30, ha='right')
for bar, score in zip(bars, f1_cl4_scores):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01, f"{score:.2f}", ha='center', va='bottom')
plt.tight_layout()
plt.show()

# Utiliser un sous-échantillon pour la recherche d'hyperparamètres
X_train_small = X_train.sample(n=20000, random_state=42)
y_train_small = y_train.loc[X_train_small.index]

# Réduire la grille pour limiter la consommation mémoire
catboost_param_grid = {
    'iterations': [100],
    'depth': [4, 6],
    'learning_rate': [0.1],
    'l2_leaf_reg': [3]
}

catboost_grid = GridSearchCV(
    estimator=CatBoostClassifier(verbose=0, random_state=42),
    param_grid=catboost_param_grid,
    scoring='f1_weighted',
    cv=2,  # Moins de folds pour économiser la mémoire
    n_jobs=-1,
    verbose=2
)

catboost_grid.fit(X_train_small, y_train_small)

print("Meilleurs hyperparamètres CatBoost :", catboost_grid.best_params_)
print("Meilleur score F1 pondéré :", catboost_grid.best_score_)

# Réentraîner CatBoost avec les hyperparamètres optimaux
catboost_best = CatBoostClassifier(
    depth=6,
    iterations=100,
    l2_leaf_reg=3,
    learning_rate=0.1,
    verbose=0,
    random_state=42
)
catboost_best.fit(X_train, y_train)

# Prédiction et évaluation
y_pred_catboost_best = catboost_best.predict(X_test)
conf_matrix_catboost_best = confusion_matrix(y_test, y_pred_catboost_best)
class_report_catboost_best = classification_report(y_test, y_pred_catboost_best)

print(conf_matrix_catboost_best)
print(class_report_catboost_best)

"""### Interprétation de la matrice de confusion et du rapport de classification (CatBoost optimisé)

#### Matrice de confusion

| Classe réelle \ Prédite | 0      | 1      | 2    | 3   | 4  |
|-------------------------|--------|--------|------|-----|----|
| **0**                   | 117388 | 6      | 0    | 0   | 0  |
| **1**                   | 4      | 29184  | 1    | 3   | 0  |
| **2**                   | 7      | 18     | 1230 | 0   | 0  |
| **3**                   | 1      | 33     | 0    | 314 | 1  |
| **4**                   | 0      | 9      | 0    | 0   | 8  |

- **Classe 0** : 117 388 instances parfaitement classées, 6 confondues avec la classe 1.
- **Classe 1** : 29 184 bien classées, quelques confusions mineures avec les classes 0, 2 et 3.
- **Classe 2** : 1 230 bien classées, 25 confondues avec les classes 0 et 1.
- **Classe 3** : 314 bien classées, 33 confondues avec la classe 1, 1 avec la classe 0, 1 avec la classe 4.
- **Classe 4** : 8 bien classées, 9 confondues avec la classe 1.

#### Rapport de classification

- **Classe 0, 1** : Précision, rappel et f1-score parfaits (1.00).
- **Classe 2** : Précision 1.00, rappel 0.98, f1-score 0.99.
- **Classe 3** : Précision 0.99, rappel 0.90, f1-score 0.94.
- **Classe 4** : Précision 0.89, rappel 0.47, f1-score 0.62 (le modèle a du mal à détecter tous les exemples de cette classe).

- **Exactitude globale** : 1.00 (très élevée).
- **Macro avg** : f1-score de 0.91, rappel de 0.87 (moyenne non pondérée).
- **Weighted avg** : f1-score de 1.00 (moyenne pondérée par le nombre d’exemples).

**Conclusion :**
Le modèle CatBoost optimisé est excellent sur les classes majoritaires, mais la détection de la classe minoritaire (classe 4) reste difficile (rappel 0.47, f1-score 0.62). La plupart des erreurs pour la classe 4 sont des confusions avec la classe 1. Le modèle reste très performant globalement, mais il pourrait être encore amélioré pour la détection des attaques rares.
"""

# Extraire le f1-score de la classe minoritaire (classe 4) pour chaque modèle, y compris CatBoost optimisé

def extract_f1_class(report, class_idx=4):
    lines = report.strip().split('\n')
    class_line = lines[2 + class_idx]
    parts = re.split(r'\s+', class_line.strip())
    if len(parts) >= 4:
        return float(parts[3])
    return None

f1_cl4_catboost_best = extract_f1_class(class_report_catboost_best)

f1_cl4_scores_all = [
    f1_cl4_rf, f1_cl4_rf_top5, f1_cl4_rf_smote, f1_cl4_catboost,
    f1_cl4_dt, f1_cl4_extra, f1_cl4_lgbm, f1_cl4_xgb, f1_cl4_mlp, f1_cl4_catboost_best
]

model_names_all = [
    'Random Forest (all features)', 'Random Forest (top 5)', 'Random Forest SMOTE+Opti',
    'CatBoost', 'Decision Tree', 'Extra Trees', 'LightGBM', 'XGBoost', 'MLP', 'CatBoost Opti'
]

plt.figure(figsize=(13, 6))
bars = plt.bar(model_names_all, f1_cl4_scores_all, color='salmon')
plt.ylabel('F1-score classe minoritaire (classe 4)')
plt.title('Comparaison des modèles sur la prédiction de la classe minoritaire')
plt.ylim(0, 1.1)
plt.xticks(rotation=30, ha='right')
for bar, score in zip(bars, f1_cl4_scores_all):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01, f"{score:.2f}", ha='center', va='bottom')
plt.tight_layout()
plt.show()

"""Ce projet a démontré l’efficacité du machine learning supervisé pour détecter automatiquement les attaques réseau. Il a mis en lumière l’importance cruciale du rééquilibrage des classes dans les datasets fortement déséquilibrés, ainsi que le rôle central du choix des modèles et de l’optimisation des hyperparamètres.

Les résultats obtenus montrent que les modèles comme Random Forest (avec SMOTE) et CatBoost (optimisé) permettent non seulement d’obtenir une excellente performance globale (f1-score > 0.98), mais aussi de mieux gérer les cas rares et critiques, souvent négligés par les approches naïves.

En production, ces modèles pourraient constituer un socle robuste pour des systèmes de détection d’intrusion (IDS) basés sur l’intelligence artificielle, capables de réagir efficacement face à un éventail d’attaques variées, même inédites.
"""